name: Build test
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm test
